// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FrameRate struct {
	ID           string `json:"id"`
	FrameRateNum int    `json:"frameRateNum"`
	FrameRateDen int    `json:"frameRateDen"`
}

type NewFrameRate struct {
	FrameRateNum int `json:"frameRateNum"`
	FrameRateDen int `json:"frameRateDen"`
}

type NewProject struct {
	Name         string  `json:"name"`
	Label        *string `json:"label"`
	Description  *string `json:"description"`
	FrameRateID  string  `json:"frameRateId"`
	ResolutionID string  `json:"resolutionId"`
}

type NewResolution struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Project struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Label       *string     `json:"label"`
	Description *string     `json:"description"`
	FrameRate   *FrameRate  `json:"frameRate"`
	Resolution  *Resolution `json:"resolution"`
}

type Resolution struct {
	ID string `json:"id"`
	X  int    `json:"x"`
	Y  int    `json:"y"`
}
